import type { Project, Task, Operario, TimeEntry, AuditLog } from "./types"

export const mockOperarios: Operario[] = [
  {
    id: "1",
    name: "María García",
    email: "maria@empresa.com",
    department: "Producción",
    skills: ["Soldadura", "Montaje", "Control de Calidad"],
    currentTasks: ["task-1", "task-3"],
    totalHours: 160,
    efficiency: 95,
  },
  {
    id: "2",
    name: "Carlos López",
    email: "carlos@empresa.com",
    department: "Mantenimiento",
    skills: ["Mecánica", "Electricidad", "Hidráulica"],
    currentTasks: ["task-2"],
    totalHours: 145,
    efficiency: 88,
  },
  {
    id: "3",
    name: "Ana Martínez",
    email: "ana@empresa.com",
    department: "Producción",
    skills: ["Pintura", "Acabados", "Inspección"],
    currentTasks: ["task-4", "task-5"],
    totalHours: 152,
    efficiency: 92,
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    projectId: "proj-1",
    title: "Soldadura de estructura principal",
    description: "Soldar la estructura metálica principal del proyecto",
    status: "in-progress",
    priority: "high",
    assignedTo: "1",
    estimatedHours: 24,
    actualHours: 16,
    startDate: "2024-01-15",
    endDate: "2024-01-20",
  },
  {
    id: "task-2",
    projectId: "proj-1",
    title: "Instalación sistema hidráulico",
    description: "Instalar y configurar el sistema hidráulico",
    status: "pending",
    priority: "medium",
    assignedTo: "2",
    estimatedHours: 16,
    actualHours: 0,
    startDate: "2024-01-22",
  },
  {
    id: "task-3",
    projectId: "proj-2",
    title: "Control de calidad inicial",
    description: "Inspección y control de calidad de materiales",
    status: "completed",
    priority: "high",
    assignedTo: "1",
    estimatedHours: 8,
    actualHours: 7,
    startDate: "2024-01-10",
    endDate: "2024-01-12",
  },
  {
    id: "task-4",
    projectId: "proj-2",
    title: "Aplicación de pintura base",
    description: "Aplicar la primera capa de pintura protectora",
    status: "in-progress",
    priority: "medium",
    assignedTo: "3",
    estimatedHours: 12,
    actualHours: 8,
    startDate: "2024-01-16",
  },
  {
    id: "task-5",
    projectId: "proj-3",
    title: "Montaje de componentes",
    description: "Ensamblar componentes según especificaciones",
    status: "pending",
    priority: "low",
    assignedTo: "3",
    estimatedHours: 20,
    actualHours: 0,
    startDate: "2024-02-01",
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Línea de Producción A",
    description: "Instalación y puesta en marcha de nueva línea de producción automatizada",
    status: "active",
    priority: "high",
    startDate: "2024-01-15",
    endDate: "2024-03-15",
    progress: 35,
    assignedOperarios: ["1", "2"],
    supervisor: "Juan Supervisor",
    department: "Producción",
    budget: 150000,
    tasks: mockTasks.filter((t) => t.projectId === "proj-1"),
  },
  {
    id: "proj-2",
    name: "Modernización Equipos",
    description: "Actualización y modernización de equipos de la planta",
    status: "active",
    priority: "medium",
    startDate: "2024-01-10",
    endDate: "2024-02-28",
    progress: 60,
    assignedOperarios: ["1", "3"],
    supervisor: "Juan Supervisor",
    department: "Mantenimiento",
    budget: 85000,
    tasks: mockTasks.filter((t) => t.projectId === "proj-2"),
  },
  {
    id: "proj-3",
    name: "Expansión Almacén",
    description: "Ampliación del área de almacenamiento y logística",
    status: "planning",
    priority: "low",
    startDate: "2024-02-01",
    endDate: "2024-04-30",
    progress: 10,
    assignedOperarios: ["3"],
    supervisor: "Juan Supervisor",
    department: "Logística",
    budget: 75000,
    tasks: mockTasks.filter((t) => t.projectId === "proj-3"),
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: "time-1",
    operarioId: "1",
    taskId: "task-1",
    projectId: "proj-1",
    startTime: "2024-01-15T08:00:00Z",
    endTime: "2024-01-15T12:00:00Z",
    hours: 4,
    description: "Trabajo en soldadura de estructura principal",
    date: "2024-01-15",
  },
  {
    id: "time-2",
    operarioId: "1",
    taskId: "task-1",
    projectId: "proj-1",
    startTime: "2024-01-15T13:00:00Z",
    endTime: "2024-01-15T17:00:00Z",
    hours: 4,
    description: "Continuación soldadura estructura",
    date: "2024-01-15",
  },
  {
    id: "time-3",
    operarioId: "2",
    taskId: "task-2",
    projectId: "proj-1",
    startTime: "2024-01-16T08:30:00Z",
    endTime: "2024-01-16T12:30:00Z",
    hours: 4,
    description: "Preparación sistema hidráulico",
    date: "2024-01-16",
  },
  {
    id: "time-4",
    operarioId: "1",
    taskId: "task-3",
    projectId: "proj-2",
    startTime: "2024-01-10T09:00:00Z",
    endTime: "2024-01-10T16:00:00Z",
    hours: 7,
    description: "Control de calidad completo de materiales",
    date: "2024-01-10",
  },
  {
    id: "time-5",
    operarioId: "3",
    taskId: "task-4",
    projectId: "proj-2",
    startTime: "2024-01-16T08:00:00Z",
    endTime: "2024-01-16T12:00:00Z",
    hours: 4,
    description: "Primera capa de pintura base",
    date: "2024-01-16",
  },
  {
    id: "time-6",
    operarioId: "3",
    taskId: "task-4",
    projectId: "proj-2",
    startTime: "2024-01-17T08:00:00Z",
    endTime: "2024-01-17T12:00:00Z",
    hours: 4,
    description: "Segunda capa de pintura base",
    date: "2024-01-17",
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    userId: "1",
    userName: "Admin Usuario",
    action: "Tarea completada",
    entityType: "task",
    entityId: "task-3",
    entityName: "Control de calidad inicial",
    changes: {
      status: { from: "in-progress", to: "completed" },
      actualHours: { from: 6, to: 7 },
    },
    timestamp: "2024-01-12T16:30:00Z",
    ipAddress: "192.168.1.100",
  },
  {
    id: "audit-2",
    userId: "2",
    userName: "Juan Supervisor",
    action: "Proyecto creado",
    entityType: "project",
    entityId: "proj-1",
    entityName: "Línea de Producción A",
    timestamp: "2024-01-15T09:00:00Z",
    ipAddress: "192.168.1.101",
  },
  {
    id: "audit-3",
    userId: "1",
    userName: "Admin Usuario",
    action: "Operario asignado",
    entityType: "task",
    entityId: "task-2",
    entityName: "Instalación sistema hidráulico",
    changes: {
      assignedTo: { from: null, to: "2" },
    },
    timestamp: "2024-01-16T10:15:00Z",
    ipAddress: "192.168.1.100",
  },
  {
    id: "audit-4",
    userId: "3",
    userName: "María García",
    action: "Tiempo registrado",
    entityType: "time-entry",
    entityId: "time-1",
    entityName: "Soldadura de estructura principal",
    changes: {
      hours: { from: 0, to: 4 },
    },
    timestamp: "2024-01-15T12:00:00Z",
    ipAddress: "192.168.1.102",
  },
  {
    id: "audit-5",
    userId: "2",
    userName: "Juan Supervisor",
    action: "Proyecto actualizado",
    entityType: "project",
    entityId: "proj-2",
    entityName: "Modernización Equipos",
    changes: {
      progress: { from: 50, to: 60 },
      status: { from: "planning", to: "active" },
    },
    timestamp: "2024-01-17T14:20:00Z",
    ipAddress: "192.168.1.101",
  },
  {
    id: "audit-6",
    userId: "1",
    userName: "Admin Usuario",
    action: "Tarea creada",
    entityType: "task",
    entityId: "task-5",
    entityName: "Montaje de componentes",
    timestamp: "2024-01-18T08:45:00Z",
    ipAddress: "192.168.1.100",
  },
]
