name: Deploy to Staging

on:
  push:
    branches: [ dev ]
  workflow_dispatch: # Permite deploy manual

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging # Requiere aprobación manual si está configurado
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build for staging
        run: pnpm build:staging
        env:
          NODE_ENV: staging
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }}

      - name: Deploy to Vercel (Staging)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--env NODE_ENV=staging'
          working-directory: ./

      - name: Run health check
        run: |
          echo "🔍 Running health check on staging..."
          # Aquí puedes agregar un health check específico para staging
          # curl -f ${{ secrets.STAGING_URL }}/api/health || exit 1

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Staging deployment successful!"
          echo "🌐 Staging URL: ${{ secrets.STAGING_URL }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Staging deployment failed!"
          echo "Please check the logs and fix the issues before merging to main."

